//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.Phone.ServiceReference, version 3.7.0.0
// 
namespace QRCodeDemo.WebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://husc.com/", ConfigurationName="WebService.WebServiceHuscSoap")]
    public interface WebServiceHuscSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/CountUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginCountUser(System.AsyncCallback callback, object asyncState);
        
        int EndCountUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/ListUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginListUser(System.AsyncCallback callback, object asyncState);
        
        QRCodeDemo.WebService.QR_CONTACT[] EndListUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/InsertNewUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginInsertNewUser(string name, string phone, string address, System.AsyncCallback callback, object asyncState);
        
        int EndInsertNewUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/SignUp", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginSignUp(string username, string password, System.AsyncCallback callback, object asyncState);
        
        int EndSignUp(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/Login", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState);
        
        int EndLogin(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/Update", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginUpdate(int id, QRCodeDemo.WebService.MyContact contact, string password, bool share, System.AsyncCallback callback, object asyncState);
        
        int EndUpdate(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/CheckUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginCheckUser(string phone, System.AsyncCallback callback, object asyncState);
        
        int EndCheckUser(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/UpdateRelatioship", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginUpdateRelatioship(int myID, int frID, bool myS, bool myU, System.AsyncCallback callback, object asyncState);
        
        int EndUpdateRelatioship(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/InsertNewRelationship", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginInsertNewRelationship(int myID, int frID, bool myU, bool myS, bool frU, bool frS, System.AsyncCallback callback, object asyncState);
        
        int EndInsertNewRelationship(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/GetContactList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetContactList(int myid, string fr_phone, System.AsyncCallback callback, object asyncState);
        
        int EndGetContactList(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://husc.com/GetInfoFriend", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.IAsyncResult BeginGetInfoFriend(int myID, int frID, System.AsyncCallback callback, object asyncState);
        
        QRCodeDemo.WebService.MyContact EndGetInfoFriend(System.IAsyncResult result);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://husc.com/")]
    public partial class QR_CONTACT : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idField;
        
        private string nameField;
        
        private string phoneField;
        
        private string addressField;
        
        private string usernameField;
        
        private string passwordField;
        
        private System.Nullable<System.DateTime> birthdayField;
        
        private string emailField;
        
        private string websiteField;
        
        private System.Nullable<bool> shareField;
        
        private QR_RELATIONSHIP[] qR_RELATIONSHIPsField;
        
        private QR_RELATIONSHIP[] qR_RELATIONSHIPs1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public System.Nullable<System.DateTime> birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<bool> share {
            get {
                return this.shareField;
            }
            set {
                this.shareField = value;
                this.RaisePropertyChanged("share");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        public QR_RELATIONSHIP[] QR_RELATIONSHIPs {
            get {
                return this.qR_RELATIONSHIPsField;
            }
            set {
                this.qR_RELATIONSHIPsField = value;
                this.RaisePropertyChanged("QR_RELATIONSHIPs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=11)]
        public QR_RELATIONSHIP[] QR_RELATIONSHIPs1 {
            get {
                return this.qR_RELATIONSHIPs1Field;
            }
            set {
                this.qR_RELATIONSHIPs1Field = value;
                this.RaisePropertyChanged("QR_RELATIONSHIPs1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://husc.com/")]
    public partial class QR_RELATIONSHIP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int id1Field;
        
        private int id2Field;
        
        private bool s1Field;
        
        private bool s2Field;
        
        private bool u1Field;
        
        private bool u2Field;
        
        private QR_CONTACT qR_CONTACTField;
        
        private QR_CONTACT qR_CONTACT1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int id1 {
            get {
                return this.id1Field;
            }
            set {
                this.id1Field = value;
                this.RaisePropertyChanged("id1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int id2 {
            get {
                return this.id2Field;
            }
            set {
                this.id2Field = value;
                this.RaisePropertyChanged("id2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool s1 {
            get {
                return this.s1Field;
            }
            set {
                this.s1Field = value;
                this.RaisePropertyChanged("s1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool s2 {
            get {
                return this.s2Field;
            }
            set {
                this.s2Field = value;
                this.RaisePropertyChanged("s2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public bool u1 {
            get {
                return this.u1Field;
            }
            set {
                this.u1Field = value;
                this.RaisePropertyChanged("u1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public bool u2 {
            get {
                return this.u2Field;
            }
            set {
                this.u2Field = value;
                this.RaisePropertyChanged("u2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public QR_CONTACT QR_CONTACT {
            get {
                return this.qR_CONTACTField;
            }
            set {
                this.qR_CONTACTField = value;
                this.RaisePropertyChanged("QR_CONTACT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public QR_CONTACT QR_CONTACT1 {
            get {
                return this.qR_CONTACT1Field;
            }
            set {
                this.qR_CONTACT1Field = value;
                this.RaisePropertyChanged("QR_CONTACT1");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.33440")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://husc.com/")]
    public partial class MyContact : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string phoneField;
        
        private string emailField;
        
        private string addressField;
        
        private string websiteField;
        
        private System.DateTime birthdayField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                this.phoneField = value;
                this.RaisePropertyChanged("phone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime birthday {
            get {
                return this.birthdayField;
            }
            set {
                this.birthdayField = value;
                this.RaisePropertyChanged("birthday");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceHuscSoapChannel : QRCodeDemo.WebService.WebServiceHuscSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CountUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CountUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ListUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QRCodeDemo.WebService.QR_CONTACT[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QRCodeDemo.WebService.QR_CONTACT[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertNewUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertNewUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SignUpCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public SignUpCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public LoginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CheckUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CheckUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateRelatioshipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public UpdateRelatioshipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertNewRelationshipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public InsertNewRelationshipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetContactListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetContactListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public int Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetInfoFriendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetInfoFriendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public QRCodeDemo.WebService.MyContact Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((QRCodeDemo.WebService.MyContact)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceHuscSoapClient : System.ServiceModel.ClientBase<QRCodeDemo.WebService.WebServiceHuscSoap>, QRCodeDemo.WebService.WebServiceHuscSoap {
        
        private BeginOperationDelegate onBeginCountUserDelegate;
        
        private EndOperationDelegate onEndCountUserDelegate;
        
        private System.Threading.SendOrPostCallback onCountUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginListUserDelegate;
        
        private EndOperationDelegate onEndListUserDelegate;
        
        private System.Threading.SendOrPostCallback onListUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertNewUserDelegate;
        
        private EndOperationDelegate onEndInsertNewUserDelegate;
        
        private System.Threading.SendOrPostCallback onInsertNewUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginSignUpDelegate;
        
        private EndOperationDelegate onEndSignUpDelegate;
        
        private System.Threading.SendOrPostCallback onSignUpCompletedDelegate;
        
        private BeginOperationDelegate onBeginLoginDelegate;
        
        private EndOperationDelegate onEndLoginDelegate;
        
        private System.Threading.SendOrPostCallback onLoginCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateDelegate;
        
        private EndOperationDelegate onEndUpdateDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginCheckUserDelegate;
        
        private EndOperationDelegate onEndCheckUserDelegate;
        
        private System.Threading.SendOrPostCallback onCheckUserCompletedDelegate;
        
        private BeginOperationDelegate onBeginUpdateRelatioshipDelegate;
        
        private EndOperationDelegate onEndUpdateRelatioshipDelegate;
        
        private System.Threading.SendOrPostCallback onUpdateRelatioshipCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertNewRelationshipDelegate;
        
        private EndOperationDelegate onEndInsertNewRelationshipDelegate;
        
        private System.Threading.SendOrPostCallback onInsertNewRelationshipCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetContactListDelegate;
        
        private EndOperationDelegate onEndGetContactListDelegate;
        
        private System.Threading.SendOrPostCallback onGetContactListCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetInfoFriendDelegate;
        
        private EndOperationDelegate onEndGetInfoFriendDelegate;
        
        private System.Threading.SendOrPostCallback onGetInfoFriendCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WebServiceHuscSoapClient() {
        }
        
        public WebServiceHuscSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceHuscSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceHuscSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceHuscSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<CountUserCompletedEventArgs> CountUserCompleted;
        
        public event System.EventHandler<ListUserCompletedEventArgs> ListUserCompleted;
        
        public event System.EventHandler<InsertNewUserCompletedEventArgs> InsertNewUserCompleted;
        
        public event System.EventHandler<SignUpCompletedEventArgs> SignUpCompleted;
        
        public event System.EventHandler<LoginCompletedEventArgs> LoginCompleted;
        
        public event System.EventHandler<UpdateCompletedEventArgs> UpdateCompleted;
        
        public event System.EventHandler<CheckUserCompletedEventArgs> CheckUserCompleted;
        
        public event System.EventHandler<UpdateRelatioshipCompletedEventArgs> UpdateRelatioshipCompleted;
        
        public event System.EventHandler<InsertNewRelationshipCompletedEventArgs> InsertNewRelationshipCompleted;
        
        public event System.EventHandler<GetContactListCompletedEventArgs> GetContactListCompleted;
        
        public event System.EventHandler<GetInfoFriendCompletedEventArgs> GetInfoFriendCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginCountUser(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCountUser(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndCountUser(System.IAsyncResult result) {
            return base.Channel.EndCountUser(result);
        }
        
        private System.IAsyncResult OnBeginCountUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginCountUser(callback, asyncState);
        }
        
        private object[] OnEndCountUser(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndCountUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCountUserCompleted(object state) {
            if ((this.CountUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CountUserCompleted(this, new CountUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CountUserAsync() {
            this.CountUserAsync(null);
        }
        
        public void CountUserAsync(object userState) {
            if ((this.onBeginCountUserDelegate == null)) {
                this.onBeginCountUserDelegate = new BeginOperationDelegate(this.OnBeginCountUser);
            }
            if ((this.onEndCountUserDelegate == null)) {
                this.onEndCountUserDelegate = new EndOperationDelegate(this.OnEndCountUser);
            }
            if ((this.onCountUserCompletedDelegate == null)) {
                this.onCountUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCountUserCompleted);
            }
            base.InvokeAsync(this.onBeginCountUserDelegate, null, this.onEndCountUserDelegate, this.onCountUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginListUser(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginListUser(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRCodeDemo.WebService.QR_CONTACT[] QRCodeDemo.WebService.WebServiceHuscSoap.EndListUser(System.IAsyncResult result) {
            return base.Channel.EndListUser(result);
        }
        
        private System.IAsyncResult OnBeginListUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginListUser(callback, asyncState);
        }
        
        private object[] OnEndListUser(System.IAsyncResult result) {
            QRCodeDemo.WebService.QR_CONTACT[] retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndListUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnListUserCompleted(object state) {
            if ((this.ListUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ListUserCompleted(this, new ListUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ListUserAsync() {
            this.ListUserAsync(null);
        }
        
        public void ListUserAsync(object userState) {
            if ((this.onBeginListUserDelegate == null)) {
                this.onBeginListUserDelegate = new BeginOperationDelegate(this.OnBeginListUser);
            }
            if ((this.onEndListUserDelegate == null)) {
                this.onEndListUserDelegate = new EndOperationDelegate(this.OnEndListUser);
            }
            if ((this.onListUserCompletedDelegate == null)) {
                this.onListUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnListUserCompleted);
            }
            base.InvokeAsync(this.onBeginListUserDelegate, null, this.onEndListUserDelegate, this.onListUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginInsertNewUser(string name, string phone, string address, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertNewUser(name, phone, address, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndInsertNewUser(System.IAsyncResult result) {
            return base.Channel.EndInsertNewUser(result);
        }
        
        private System.IAsyncResult OnBeginInsertNewUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string name = ((string)(inValues[0]));
            string phone = ((string)(inValues[1]));
            string address = ((string)(inValues[2]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginInsertNewUser(name, phone, address, callback, asyncState);
        }
        
        private object[] OnEndInsertNewUser(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndInsertNewUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertNewUserCompleted(object state) {
            if ((this.InsertNewUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertNewUserCompleted(this, new InsertNewUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertNewUserAsync(string name, string phone, string address) {
            this.InsertNewUserAsync(name, phone, address, null);
        }
        
        public void InsertNewUserAsync(string name, string phone, string address, object userState) {
            if ((this.onBeginInsertNewUserDelegate == null)) {
                this.onBeginInsertNewUserDelegate = new BeginOperationDelegate(this.OnBeginInsertNewUser);
            }
            if ((this.onEndInsertNewUserDelegate == null)) {
                this.onEndInsertNewUserDelegate = new EndOperationDelegate(this.OnEndInsertNewUser);
            }
            if ((this.onInsertNewUserCompletedDelegate == null)) {
                this.onInsertNewUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertNewUserCompleted);
            }
            base.InvokeAsync(this.onBeginInsertNewUserDelegate, new object[] {
                        name,
                        phone,
                        address}, this.onEndInsertNewUserDelegate, this.onInsertNewUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginSignUp(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSignUp(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndSignUp(System.IAsyncResult result) {
            return base.Channel.EndSignUp(result);
        }
        
        private System.IAsyncResult OnBeginSignUp(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginSignUp(username, password, callback, asyncState);
        }
        
        private object[] OnEndSignUp(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndSignUp(result);
            return new object[] {
                    retVal};
        }
        
        private void OnSignUpCompleted(object state) {
            if ((this.SignUpCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SignUpCompleted(this, new SignUpCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SignUpAsync(string username, string password) {
            this.SignUpAsync(username, password, null);
        }
        
        public void SignUpAsync(string username, string password, object userState) {
            if ((this.onBeginSignUpDelegate == null)) {
                this.onBeginSignUpDelegate = new BeginOperationDelegate(this.OnBeginSignUp);
            }
            if ((this.onEndSignUpDelegate == null)) {
                this.onEndSignUpDelegate = new EndOperationDelegate(this.OnEndSignUp);
            }
            if ((this.onSignUpCompletedDelegate == null)) {
                this.onSignUpCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSignUpCompleted);
            }
            base.InvokeAsync(this.onBeginSignUpDelegate, new object[] {
                        username,
                        password}, this.onEndSignUpDelegate, this.onSignUpCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginLogin(username, password, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndLogin(System.IAsyncResult result) {
            return base.Channel.EndLogin(result);
        }
        
        private System.IAsyncResult OnBeginLogin(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string password = ((string)(inValues[1]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginLogin(username, password, callback, asyncState);
        }
        
        private object[] OnEndLogin(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndLogin(result);
            return new object[] {
                    retVal};
        }
        
        private void OnLoginCompleted(object state) {
            if ((this.LoginCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.LoginCompleted(this, new LoginCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void LoginAsync(string username, string password) {
            this.LoginAsync(username, password, null);
        }
        
        public void LoginAsync(string username, string password, object userState) {
            if ((this.onBeginLoginDelegate == null)) {
                this.onBeginLoginDelegate = new BeginOperationDelegate(this.OnBeginLogin);
            }
            if ((this.onEndLoginDelegate == null)) {
                this.onEndLoginDelegate = new EndOperationDelegate(this.OnEndLogin);
            }
            if ((this.onLoginCompletedDelegate == null)) {
                this.onLoginCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnLoginCompleted);
            }
            base.InvokeAsync(this.onBeginLoginDelegate, new object[] {
                        username,
                        password}, this.onEndLoginDelegate, this.onLoginCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginUpdate(int id, QRCodeDemo.WebService.MyContact contact, string password, bool share, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdate(id, contact, password, share, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndUpdate(System.IAsyncResult result) {
            return base.Channel.EndUpdate(result);
        }
        
        private System.IAsyncResult OnBeginUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int id = ((int)(inValues[0]));
            QRCodeDemo.WebService.MyContact contact = ((QRCodeDemo.WebService.MyContact)(inValues[1]));
            string password = ((string)(inValues[2]));
            bool share = ((bool)(inValues[3]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginUpdate(id, contact, password, share, callback, asyncState);
        }
        
        private object[] OnEndUpdate(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateCompleted(object state) {
            if ((this.UpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateCompleted(this, new UpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateAsync(int id, QRCodeDemo.WebService.MyContact contact, string password, bool share) {
            this.UpdateAsync(id, contact, password, share, null);
        }
        
        public void UpdateAsync(int id, QRCodeDemo.WebService.MyContact contact, string password, bool share, object userState) {
            if ((this.onBeginUpdateDelegate == null)) {
                this.onBeginUpdateDelegate = new BeginOperationDelegate(this.OnBeginUpdate);
            }
            if ((this.onEndUpdateDelegate == null)) {
                this.onEndUpdateDelegate = new EndOperationDelegate(this.OnEndUpdate);
            }
            if ((this.onUpdateCompletedDelegate == null)) {
                this.onUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateDelegate, new object[] {
                        id,
                        contact,
                        password,
                        share}, this.onEndUpdateDelegate, this.onUpdateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginCheckUser(string phone, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCheckUser(phone, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndCheckUser(System.IAsyncResult result) {
            return base.Channel.EndCheckUser(result);
        }
        
        private System.IAsyncResult OnBeginCheckUser(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string phone = ((string)(inValues[0]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginCheckUser(phone, callback, asyncState);
        }
        
        private object[] OnEndCheckUser(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndCheckUser(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCheckUserCompleted(object state) {
            if ((this.CheckUserCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CheckUserCompleted(this, new CheckUserCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CheckUserAsync(string phone) {
            this.CheckUserAsync(phone, null);
        }
        
        public void CheckUserAsync(string phone, object userState) {
            if ((this.onBeginCheckUserDelegate == null)) {
                this.onBeginCheckUserDelegate = new BeginOperationDelegate(this.OnBeginCheckUser);
            }
            if ((this.onEndCheckUserDelegate == null)) {
                this.onEndCheckUserDelegate = new EndOperationDelegate(this.OnEndCheckUser);
            }
            if ((this.onCheckUserCompletedDelegate == null)) {
                this.onCheckUserCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckUserCompleted);
            }
            base.InvokeAsync(this.onBeginCheckUserDelegate, new object[] {
                        phone}, this.onEndCheckUserDelegate, this.onCheckUserCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginUpdateRelatioship(int myID, int frID, bool myS, bool myU, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginUpdateRelatioship(myID, frID, myS, myU, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndUpdateRelatioship(System.IAsyncResult result) {
            return base.Channel.EndUpdateRelatioship(result);
        }
        
        private System.IAsyncResult OnBeginUpdateRelatioship(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int myID = ((int)(inValues[0]));
            int frID = ((int)(inValues[1]));
            bool myS = ((bool)(inValues[2]));
            bool myU = ((bool)(inValues[3]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginUpdateRelatioship(myID, frID, myS, myU, callback, asyncState);
        }
        
        private object[] OnEndUpdateRelatioship(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndUpdateRelatioship(result);
            return new object[] {
                    retVal};
        }
        
        private void OnUpdateRelatioshipCompleted(object state) {
            if ((this.UpdateRelatioshipCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateRelatioshipCompleted(this, new UpdateRelatioshipCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void UpdateRelatioshipAsync(int myID, int frID, bool myS, bool myU) {
            this.UpdateRelatioshipAsync(myID, frID, myS, myU, null);
        }
        
        public void UpdateRelatioshipAsync(int myID, int frID, bool myS, bool myU, object userState) {
            if ((this.onBeginUpdateRelatioshipDelegate == null)) {
                this.onBeginUpdateRelatioshipDelegate = new BeginOperationDelegate(this.OnBeginUpdateRelatioship);
            }
            if ((this.onEndUpdateRelatioshipDelegate == null)) {
                this.onEndUpdateRelatioshipDelegate = new EndOperationDelegate(this.OnEndUpdateRelatioship);
            }
            if ((this.onUpdateRelatioshipCompletedDelegate == null)) {
                this.onUpdateRelatioshipCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateRelatioshipCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateRelatioshipDelegate, new object[] {
                        myID,
                        frID,
                        myS,
                        myU}, this.onEndUpdateRelatioshipDelegate, this.onUpdateRelatioshipCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginInsertNewRelationship(int myID, int frID, bool myU, bool myS, bool frU, bool frS, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertNewRelationship(myID, frID, myU, myS, frU, frS, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndInsertNewRelationship(System.IAsyncResult result) {
            return base.Channel.EndInsertNewRelationship(result);
        }
        
        private System.IAsyncResult OnBeginInsertNewRelationship(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int myID = ((int)(inValues[0]));
            int frID = ((int)(inValues[1]));
            bool myU = ((bool)(inValues[2]));
            bool myS = ((bool)(inValues[3]));
            bool frU = ((bool)(inValues[4]));
            bool frS = ((bool)(inValues[5]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginInsertNewRelationship(myID, frID, myU, myS, frU, frS, callback, asyncState);
        }
        
        private object[] OnEndInsertNewRelationship(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndInsertNewRelationship(result);
            return new object[] {
                    retVal};
        }
        
        private void OnInsertNewRelationshipCompleted(object state) {
            if ((this.InsertNewRelationshipCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertNewRelationshipCompleted(this, new InsertNewRelationshipCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertNewRelationshipAsync(int myID, int frID, bool myU, bool myS, bool frU, bool frS) {
            this.InsertNewRelationshipAsync(myID, frID, myU, myS, frU, frS, null);
        }
        
        public void InsertNewRelationshipAsync(int myID, int frID, bool myU, bool myS, bool frU, bool frS, object userState) {
            if ((this.onBeginInsertNewRelationshipDelegate == null)) {
                this.onBeginInsertNewRelationshipDelegate = new BeginOperationDelegate(this.OnBeginInsertNewRelationship);
            }
            if ((this.onEndInsertNewRelationshipDelegate == null)) {
                this.onEndInsertNewRelationshipDelegate = new EndOperationDelegate(this.OnEndInsertNewRelationship);
            }
            if ((this.onInsertNewRelationshipCompletedDelegate == null)) {
                this.onInsertNewRelationshipCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertNewRelationshipCompleted);
            }
            base.InvokeAsync(this.onBeginInsertNewRelationshipDelegate, new object[] {
                        myID,
                        frID,
                        myU,
                        myS,
                        frU,
                        frS}, this.onEndInsertNewRelationshipDelegate, this.onInsertNewRelationshipCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginGetContactList(int myid, string fr_phone, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetContactList(myid, fr_phone, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        int QRCodeDemo.WebService.WebServiceHuscSoap.EndGetContactList(System.IAsyncResult result) {
            return base.Channel.EndGetContactList(result);
        }
        
        private System.IAsyncResult OnBeginGetContactList(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int myid = ((int)(inValues[0]));
            string fr_phone = ((string)(inValues[1]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginGetContactList(myid, fr_phone, callback, asyncState);
        }
        
        private object[] OnEndGetContactList(System.IAsyncResult result) {
            int retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndGetContactList(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetContactListCompleted(object state) {
            if ((this.GetContactListCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetContactListCompleted(this, new GetContactListCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetContactListAsync(int myid, string fr_phone) {
            this.GetContactListAsync(myid, fr_phone, null);
        }
        
        public void GetContactListAsync(int myid, string fr_phone, object userState) {
            if ((this.onBeginGetContactListDelegate == null)) {
                this.onBeginGetContactListDelegate = new BeginOperationDelegate(this.OnBeginGetContactList);
            }
            if ((this.onEndGetContactListDelegate == null)) {
                this.onEndGetContactListDelegate = new EndOperationDelegate(this.OnEndGetContactList);
            }
            if ((this.onGetContactListCompletedDelegate == null)) {
                this.onGetContactListCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetContactListCompleted);
            }
            base.InvokeAsync(this.onBeginGetContactListDelegate, new object[] {
                        myid,
                        fr_phone}, this.onEndGetContactListDelegate, this.onGetContactListCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult QRCodeDemo.WebService.WebServiceHuscSoap.BeginGetInfoFriend(int myID, int frID, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetInfoFriend(myID, frID, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        QRCodeDemo.WebService.MyContact QRCodeDemo.WebService.WebServiceHuscSoap.EndGetInfoFriend(System.IAsyncResult result) {
            return base.Channel.EndGetInfoFriend(result);
        }
        
        private System.IAsyncResult OnBeginGetInfoFriend(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int myID = ((int)(inValues[0]));
            int frID = ((int)(inValues[1]));
            return ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).BeginGetInfoFriend(myID, frID, callback, asyncState);
        }
        
        private object[] OnEndGetInfoFriend(System.IAsyncResult result) {
            QRCodeDemo.WebService.MyContact retVal = ((QRCodeDemo.WebService.WebServiceHuscSoap)(this)).EndGetInfoFriend(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetInfoFriendCompleted(object state) {
            if ((this.GetInfoFriendCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetInfoFriendCompleted(this, new GetInfoFriendCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetInfoFriendAsync(int myID, int frID) {
            this.GetInfoFriendAsync(myID, frID, null);
        }
        
        public void GetInfoFriendAsync(int myID, int frID, object userState) {
            if ((this.onBeginGetInfoFriendDelegate == null)) {
                this.onBeginGetInfoFriendDelegate = new BeginOperationDelegate(this.OnBeginGetInfoFriend);
            }
            if ((this.onEndGetInfoFriendDelegate == null)) {
                this.onEndGetInfoFriendDelegate = new EndOperationDelegate(this.OnEndGetInfoFriend);
            }
            if ((this.onGetInfoFriendCompletedDelegate == null)) {
                this.onGetInfoFriendCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetInfoFriendCompleted);
            }
            base.InvokeAsync(this.onBeginGetInfoFriendDelegate, new object[] {
                        myID,
                        frID}, this.onEndGetInfoFriendDelegate, this.onGetInfoFriendCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override QRCodeDemo.WebService.WebServiceHuscSoap CreateChannel() {
            return new WebServiceHuscSoapClientChannel(this);
        }
        
        private class WebServiceHuscSoapClientChannel : ChannelBase<QRCodeDemo.WebService.WebServiceHuscSoap>, QRCodeDemo.WebService.WebServiceHuscSoap {
            
            public WebServiceHuscSoapClientChannel(System.ServiceModel.ClientBase<QRCodeDemo.WebService.WebServiceHuscSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginCountUser(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("CountUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCountUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CountUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginListUser(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("ListUser", _args, callback, asyncState);
                return _result;
            }
            
            public QRCodeDemo.WebService.QR_CONTACT[] EndListUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                QRCodeDemo.WebService.QR_CONTACT[] _result = ((QRCodeDemo.WebService.QR_CONTACT[])(base.EndInvoke("ListUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertNewUser(string name, string phone, string address, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = name;
                _args[1] = phone;
                _args[2] = address;
                System.IAsyncResult _result = base.BeginInvoke("InsertNewUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertNewUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertNewUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginSignUp(string username, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("SignUp", _args, callback, asyncState);
                return _result;
            }
            
            public int EndSignUp(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("SignUp", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginLogin(string username, string password, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = username;
                _args[1] = password;
                System.IAsyncResult _result = base.BeginInvoke("Login", _args, callback, asyncState);
                return _result;
            }
            
            public int EndLogin(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Login", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdate(int id, QRCodeDemo.WebService.MyContact contact, string password, bool share, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = id;
                _args[1] = contact;
                _args[2] = password;
                _args[3] = share;
                System.IAsyncResult _result = base.BeginInvoke("Update", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("Update", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCheckUser(string phone, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = phone;
                System.IAsyncResult _result = base.BeginInvoke("CheckUser", _args, callback, asyncState);
                return _result;
            }
            
            public int EndCheckUser(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("CheckUser", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginUpdateRelatioship(int myID, int frID, bool myS, bool myU, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[4];
                _args[0] = myID;
                _args[1] = frID;
                _args[2] = myS;
                _args[3] = myU;
                System.IAsyncResult _result = base.BeginInvoke("UpdateRelatioship", _args, callback, asyncState);
                return _result;
            }
            
            public int EndUpdateRelatioship(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("UpdateRelatioship", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertNewRelationship(int myID, int frID, bool myU, bool myS, bool frU, bool frS, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[6];
                _args[0] = myID;
                _args[1] = frID;
                _args[2] = myU;
                _args[3] = myS;
                _args[4] = frU;
                _args[5] = frS;
                System.IAsyncResult _result = base.BeginInvoke("InsertNewRelationship", _args, callback, asyncState);
                return _result;
            }
            
            public int EndInsertNewRelationship(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("InsertNewRelationship", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetContactList(int myid, string fr_phone, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = myid;
                _args[1] = fr_phone;
                System.IAsyncResult _result = base.BeginInvoke("GetContactList", _args, callback, asyncState);
                return _result;
            }
            
            public int EndGetContactList(System.IAsyncResult result) {
                object[] _args = new object[0];
                int _result = ((int)(base.EndInvoke("GetContactList", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetInfoFriend(int myID, int frID, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = myID;
                _args[1] = frID;
                System.IAsyncResult _result = base.BeginInvoke("GetInfoFriend", _args, callback, asyncState);
                return _result;
            }
            
            public QRCodeDemo.WebService.MyContact EndGetInfoFriend(System.IAsyncResult result) {
                object[] _args = new object[0];
                QRCodeDemo.WebService.MyContact _result = ((QRCodeDemo.WebService.MyContact)(base.EndInvoke("GetInfoFriend", _args, result)));
                return _result;
            }
        }
    }
}
