<?xml version="1.0" encoding="utf-8"?><Database Name="Contact" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Contact.mssql.somee.com;Initial Catalog=Contact;Persist Security Info=False;User ID=manhtuan_ur_SQLLogin_1;Packet Size=4096;Workstation ID=Contact.mssql.somee.com" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ContactConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.QR_CONTACT" Member="QR_CONTACTs">
    <Type Name="QR_CONTACT">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phone" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
</Database>